/*
 * Read-data flux stream and INDEX pulse, generated by the RMT peripheral.
 *
 * One endless RMT transmission (DMA) is the virtual 300 rpm rotation: it
 * plays 100000 bitcells per revolution from the track selected by the
 * current cylinder and the live SIDE level. A second RMT channel loops the
 * INDEX pulse (3 ms per 200 ms), started in sync with the data stream.
 * Both channels run all the time; flux_gate() connects them to the pins
 * (GPIO41 RDATA, GPIO1 INDEX) or parks the pins LOW (released).
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"

#define FLUX_RESOLUTION_HZ  10000000    /* 0.1 us per RMT tick */
#define FLUX_REV_TICKS      2000000     /* one revolution: 200 ms (300 rpm) */
#define FLUX_PULSE_TICKS    8           /* 0.8 us /RDATA pulse */
#define INDEX_PULSE_MS      3

/* Start both RMT channels with the outputs gated off. */
esp_err_t flux_stream_init(void);

/* Connect (true) or release (false) RDATA and INDEX. ISR/IRAM safe. */
void flux_gate(bool rdata, bool index);

/* Revolutions played since start (virtual index counter). */
uint32_t flux_revolutions(void);

/*
 * ST: every track is spread over exactly 200 ms and INDEX is a hardware
 * loop of 200 ms. HFE (native timing): tracks play at the cell times of
 * the file (hfe.h packed tracks); a revolution lasts as long as the track
 * and INDEX is placed on the exact RMT tick where the track wraps.
 * Changing the mode restarts both channels together (task context; call
 * right after an ST <-> HFE disk change).
 */
typedef enum { FLUX_MODE_ST, FLUX_MODE_HFE } flux_mode_t;
esp_err_t flux_stream_set_mode(flux_mode_t mode);
flux_mode_t flux_stream_mode(void);

typedef struct {
    uint32_t late_pulses;       /* INDEX pulses that came after their boundary */
    uint32_t late_max_us;
    uint32_t lost_boundaries;   /* boundary queue overflow (never expected) */
} flux_hfe_stats_t;
void flux_hfe_stats(flux_hfe_stats_t *st);
