/*
 * Read-data flux stream and INDEX pulse, generated by the RMT peripheral.
 *
 * One endless RMT transmission (DMA) is the virtual 300 rpm rotation: it
 * plays 100000 bitcells per revolution from the track selected by the
 * current cylinder and the live SIDE level. A second RMT channel loops the
 * INDEX pulse (3 ms per 200 ms), started in sync with the data stream.
 * Both channels run all the time; flux_gate() connects them to the pins
 * (GPIO41 RDATA, GPIO1 INDEX) or parks the pins LOW (released).
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"

#define FLUX_RESOLUTION_HZ  10000000    /* 0.1 us per RMT tick */
#define FLUX_CELL_TICKS     20          /* 2 us MFM bitcell */
#define FLUX_PULSE_TICKS    8           /* 0.8 us /RDATA pulse */
#define INDEX_PULSE_MS      3

/* Start both RMT channels with the outputs gated off. */
esp_err_t flux_stream_init(void);

/* Connect (true) or release (false) RDATA and INDEX. ISR/IRAM safe. */
void flux_gate(bool rdata, bool index);

/* Revolutions played since start (virtual index counter). */
uint32_t flux_revolutions(void);
